name: Send Discord webhook on push

on:
  workflow_dispatch:
    
  push:
    branches:
      - main # Replace with the name of your branch

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        embed-title: ${{ github.event.repository.name }}
        embed-description: "A new commit has been pushed to the Cursed Creations archive: ${{ github.event.head_commit.message }}"
        username: "Github Webhook"
        avatar-url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
