name: Send Discord webhook on push

on:
  workflow_dispatch:
    
  push:
    branches:
      - main # Replace with the name of your branch
jobs:
  message:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        embed-title: ${{ github.event.head_commit.message }}
        embed-description: "A new commit has been pushed to the repository."
        username: "Github Actions"
        avatar-url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png